[package]
name = "ed25519n"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "*", optional = true }
env_logger = { version = "*", optional = true }
modmath = "0.1.2"
fixed-bigint = { version = "0.1.17", features=["use-unsafe"], optional=true }
num-traits = {  version = "0.2" , default-features = false }
hmac-sha512 = { version = "1", features = ["opt_size"] }
num-bigint = { version = "0.4.6", optional = true }
bnum = { version = "0.13.0", optional = true, features = ["numtraits"] }
crypto-bigint = { version = "0.6.1", optional = true }
ibig = { version = "0.3.6", optional = true }

num-bigint_patched = { package = "num-bigint", git = "https://github.com/kaidokert/num-bigint.git" , tag = "v0.4.6_patch", optional = true }
bnum_patched = { package = "bnum",features = ["numtraits"]  , git = "https://github.com/kaidokert/bnum.git", tag = "v0.12.1_patch", optional = true }
crypto-bigint_patched = { package = "crypto-bigint", git = "https://github.com/kaidokert/crypto-bigint.git" , tag = "v0.6.1_rsa_patch_1", optional = true }
ibig_patched = { package = "ibig", git = "https://github.com/kaidokert/ibig-rs.git" , tag = "v0.3.6_patch", optional = true }
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }

[features]
default = ["std"]
std = ["log", "env_logger"]
precomputed = []
fixed-bigint = ["dep:fixed-bigint"]
fixed-bigint-u64 = ["fixed-bigint"]
montgomery = []
montgomery-euclidean = ["montgomery"]
montgomery-hensels = ["montgomery"]
num-bigint = ["dep:num-bigint"]
bnum = ["dep:bnum"]
crypto-bigint = ["dep:crypto-bigint"]
ibig = ["dep:ibig"]
num-bigint-patched = ["dep:num-bigint_patched"]
bnum-patched = ["dep:bnum_patched"]
crypto-bigint-patched = ["dep:crypto-bigint_patched"]
ibig-patched = ["dep:ibig_patched"]

[[bin]]
name = "verify_baked"
required-features = ["fixed-bigint"]

[[bin]]
name = "benchmark"

[[bin]]
name = "test_montgomery_performance"

[patch.crates-io]
modmath = { path = "deps/modmath-rs" }
