[package]
name = "ed25519_heapless"
version = "0.0.1"
edition = "2024"
description = "Ed25519 signature verification, generic over bigint backends"
license = "GPL-3.0-only"
repository = "https://github.com/kaidokert/ed25519"
readme = "../README.md"
keywords = ["ed25519", "signature", "verification", "no_std", "embedded"]
categories = ["cryptography", "no-std", "no-std::no-alloc"]

[dependencies]
log = { version = "0.4", optional = true }
env_logger = { version = "0.11", optional = true }
modmath = { version = "0.1.5", features = ["wide-mul"] }
fixed-bigint = { version = "0.2.5", features=["use-unsafe"], optional=true }
num-traits = {  version = "0.2" , default-features = false }
hmac-sha512 = { version = "1", default-features = false, features = ["opt_size"] }
signature = { version = "2.2", default-features = false }

[features]
default = ["std"]
std = ["log", "env_logger"]
defmt = []
fixed-bigint = ["dep:fixed-bigint"]
fixed-bigint-u64 = ["fixed-bigint"]
fixed-bigint-256 = ["fixed-bigint"]
fixed-bigint-u8 = ["fixed-bigint"]

[[bin]]
name = "verify_baked"
required-features = ["fixed-bigint"]

[[bin]]
name = "verify"
required-features = ["fixed-bigint"]

[[bin]]
name = "sign"

[[bin]]
name = "keygen"
